import { PlusButton } from './product/styled';

export {default as Auth} from './auth'
export {default as Menu} from './menu'
export {default as Header} from './header'
export {default as Chat} from './chat'
export {default as Filter} from './filter/'
export {default as Home} from './main/'
export {default as Cart} from './cart'
export {default as Product} from './product'
export {default as Loader} from './loader'
export {default as Refer} from './main/referFriend'
export {default as Notification} from './main/notification'
export {default as ChangeAddress} from './main/changeAddress'
export {default as Created} from './main/order'
export {default as RoutesWindow} from './main/routes'
export {default as Edit} from './main/order/idetOrder/edit'
export {default as NoOrder} from './main/order/noOrder'
export {default as EditOrder} from './main/order/idetOrder/editOrder'
export {default as NewAddress} from './main/settings/newAddress'
export {default as CartButton} from './cart/cartButton'
export {default as NotEnoughProduct} from './cart/notEnoughProduct'
export {default as CheckoutAddress} from './checkout/checkoutAddress'
export {default as MergeOrder} from './checkout/mergeOrder'
export {default as Change} from './checkout/change'
export {default as ChangeNumber} from './main/changeNumber'

export {default as AnimatePage} from './common/animation/animatePage'
export {default as FadeInWrapper} from './common/animation/fadeInWrapper'
export {default as AnimatedPulse} from './common/animation/animatePulse'
export {default as HeightAnimation} from './common/animation/heightAnimate'


