module.exports = {
    productCategoriesForApp :[
        'Diamond',
        'Platinum',
        'Gold',
        'Iron',
        'LSO',
        'Silver',
        'Bronze',
        'Bronze',
        '🚬 Prerolls',
        'Shatter',
        'Budder',
        'RSO',
        'Live Resin',
        '99% THC Distillate',
        '99% CBD',
        'Chocolates',
        'Mushroom Microdose',
        'Whole Mushrooms',
        'Mushroom Choco Bars',
        'Microdose Mushrooms',
        'Mushroom Edibles',
        'Mushrooms (-)',
        'Mushrooms',
        'Mushrooms (+)',
        'Mushrooms (µ)',
        'Gummies',
        'Drinks',
        'Cartridges',
        'Devices',
        'Starter Kit',
        'Pods (Dab)',
        'Starter Kit (Dab)',
        'Device',
        'Disposables'
    ],
    wkColsForApp: {
        "Wk1": 8,
        "Wk2": 9,
        "Wk3": 10,
        "Wk4": 11
    },
    categoryColForApp: 6,
    prodSheetNameForApp: "for app 3.0"
};