module.exports = {
    productCategories :[
        'Diamond',
        'Platinum',
        'Gold',
        'Iron',
        'LSO',
        'Silver',
        'Bronze',
        'Bronze',
        '🚬 Prerolls',
        'Shatter',
        'Budder',
        'RSO',
        'Live Resin',
        '99% THC Distillate',
        '99% CBD',
        'Chocolates',
        'Mushroom Microdose',
        'Whole Mushrooms',
        'Mushroom Choco Bars',
        'Mushrooms (-)',
        'Mushrooms',
        'Mushrooms (+)',
        'Mushrooms (µ)',
        'Gummies',
        'Drinks',
        'Cartridges',
        'Devices',
        'Starter Kit',
        'Pods (Dab)',
        'Starter Kit (Dab)',
        'Device',
        'Disposables'
    ],
    wkCols: {
        "Wk1": 5,
        "Wk2": 6,
        "Wk3": 7,
        "Wk4": 8
    },
    categoryCol: 3,
    prodSheetName: "Sheet1",
};