server {
  listen 80;
  location ~* /.well-known/apple-developer-merchantid-domain-association$ {
      root   /usr/share/nginx/html;
      try_files /.well-known/apple-developer-merchantid-domain-association = 404;
  }

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}
